# This is a config sample file for high level API.
# Please create the config file in $HOME/.config/cedarkit.yaml
# Or set environment variable CEDARKIT_CONFIG for its path.

cmadaas:
  auth:
    user: user name
    password: user password
  server:
    music_server: music server ip
    music_port: music server port
    music_connTimeout: 3  # connection time out, seconds
    music_readTimeout: 3000  # read time out, seconds
    music_ServiceId: music service id
